# Generated by Django 4.2.9 on 2024-02-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0003_reservation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
    ]
