# Generated by Django 4.2.9 on 2024-02-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0004_employees"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
            ],
        ),
    ]
