# Generated by Django 4.2.9 on 2024-02-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0005_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelForTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("booking_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
