# Generated by Django 4.2.9 on 2024-02-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0006_modelfortest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["price"], name="demoapp_boo_price_ca9cba_idx")
                ],
            },
        ),
    ]
