# Generated by Django 4.2.10 on 2024-02-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0009_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserComments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("comment", models.CharField(max_length=1000)),
            ],
        ),
    ]
